Document: bashdb
Title: Debian bashdb Manual
Author: <insert document author here>
Abstract: This manual describes what bashdb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bashdb/bashdb.sgml.gz

Format: postscript
Files: /usr/share/doc/bashdb/bashdb.ps.gz

Format: text
Files: /usr/share/doc/bashdb/bashdb.text.gz

Format: HTML
Index: /usr/share/doc/bashdb/html/index.html
Files: /usr/share/doc/bashdb/html/*.html
